# Jekyll
server: true
auto: true
markdown: rdiscount
pygments: true
permalink: /:title.html

# Conference info
conf:
  name: "Front in Recife"
  description: "Let us together make a great day, dedicated to improving our knowledge related to front-end development, together with great speakers from local and national. This year we will talk about SEO, Responsive, cross-platform mobile web, HTML, JavaScript, CSS. See you there!"
  date: "14 de Dezembro"
  price: "R$ 60"
  address: "Rua Itatiaia, 318 — Apipucos — Recife, Pernambuco"
  venue: "Faculdade Marista"
  city: "Recife"

# Site info
site:
  url: "http://frontinrecife.com.br"
  favicon: "http://braziljs.org/favicon.ico"
  googleanalytics: "UA-44683857-1"
  images:
    cover: "img/dennis.jpg"
    facebook: "http://frontinrecife.com.br/img/fb.png"

# Active sections on the website
sections:
  about: true
  speakers: true
  city: true
  location: true
  schedule: false
  sponsors: false
  partners: true
  contact: false

# The entire schedule
schedule:
  -
    name: "Check-in / Breakfast"
    time: "9h00"
  -
    name: "Almir Filho (RJ)"
    photo: "http://graph.facebook.com/almirflorenciofilho/picture?type=large"
    bio: "Desenvolvedor na Globo.com e co-fundador do Loop Infinito, onde compartilha seu conhecimento sobre front-end. Graduado e mestrando em Ciência da Computação, é extremamente interessado pelos padrões web e produtividade."
    company: "Globo.com / Loopinfinito"
    twitter: "almirfilho"
    presentation:
      title: ""
      description: ""
      time: "10h00"
  -
    name: "Ciro Nunes"
    photo: "/img/speakers/ciro.jpg"
    bio: "Já foi responsável pelos maiores e-commerces da América Latina como Submarino, Shoptime e Americanas e foi o head Front-end Engineer e Agile Coach da Kanui (Rocket Internet). É membro/colaborador da comunidade AngularJS, framework JavaScript o qual escreve sobre em seu blog e organiza um meetup em São Paulo."
    company: "AngularJS São Paulo"
    twitter: "cironunesdev"
    presentation:
      title: "Pare de fazer sites, faça aplicações!"
      description: "Não existe coisa pior para um desenvolvedor do que ter que dar manutenção em código legado. Aquele código que ninguém quer mexer, difícil de entender, acoplado e o pior: sem testes! Nosso código pode chegar rapidamente nesse estado quando desenvolvemos sites. Vamos falar sobre como tratar nossos projetos como aplicações web. Boas práticas de desenvolvimento Front-end como testes automatizados e guias de estilo, além ferramentas para deixar nossos projetos incrivelmente fáceis de manter, aumentando a produtividade."
      time: "11h00"
  -
    name: "Davidson Fellipe"
    photo: "http://graph.facebook.com/fellipe/picture?type=large"
    bio: "Um dos criadores da BrazilJS Foundation, trabalha na equipe de esportes da Globo.com, onde já se envolveu com projetos para o Globoesporte.com, Futpédia, Tempo Real, Eu Atleta e Sportv. É bastante envolvido com a comunidade JS, sendo o fundador e moderador do riojs e pernambucojs, além de organizar o Front in BH. Graduado em engenharia da computação pela UPE, técnico em eletrônica pelo IFPE e Mestrando em Informática na PUC-Rio."
    company: "Globo.com (RJ)"
    twitter: "davidsonfellipe"
    presentation:
      title: ""
      description: ""
      time: "11h00"
  -
    name: "Guilherme Farias"
    photo: "/img/speakers/guilherme-farias.jpg"
    bio: "É desenvolvedor web com foco no client-side e mobile, entusiasta Javascript, Engenheiro FrontEnd na MGR Tecnologia, nas horas vagas está envolvido com projetos open-source e ligado no que rola de mais novo no mundo do JS."
    company: "MGR Tecnologia (PE)"
    twitter: "guiky"
    presentation:
      title: ""
      description: ""
      time: "13h00"
  -
    name: "Leo Balter"
    photo: "http://graph.facebook.com/leobalter/picture?type=large"
    bio: "É advogado por formação e desenvolvedor por diversão. Entusiasta de tecnologias front-end e pela Open Web, está conectado a diversas comunidades da área em todo o mundo. Também é representante Mozilla e lead front-end na Estante Virtual, divide o tempo com outras paixões, entre elas a música e longboard."
    company: "Mozilla / Estante Virtual (RJ)"
    twitter: "leobalter"
    presentation:
      title: ""
      description: ""
      time: "13h00"
  -
    name: "Luiz Tiago"
    photo: "/img/speakers/luiz-tiago.jpg"
    bio: "Pós-graduado em Desenvolvimento de Aplicações Móveis no CESAR e Graduado em Sistemas para Internet na Faculdade Marista, atua na área de web desde 2001. Co-fundador do jQueryBrasil e Pernambuco.JS, atualmente é CTO da MGR Tecnologia."
    company: "MGR Tecnologia (PE)"
    twitter: "luiztiago"
    presentation:
      title: ""
      description: ""
      time: "13h00"
  -
    name: "Mailson Lira"
    photo: "/img/speakers/mailson.jpg"
    bio: "Desenvolvedor de software do Instituto Nokia de Tecnologia (INdT). Participou do desenvolvimento da versão HTML5 do Incredible Circus. Contribui para o KDE. Formado em Ciência da Computação pela UFPE."
    company: "Instituto Nokia de Tecnologia - INdT (PE)"
    twitter: "omailson"
    presentation:
      title: "Desafios de se criar um jogo em HTML5"
      description: "em breve mais detalhes"
      time: "14h00"
  -
    name: "Pedro Marins"
    photo: "/img/speakers/pedro.jpg"
    bio: "Desenvolvedor com vasta experiência em diversos projetos de características variadas. Tem Formação acadêmica pela UniRio. Atualmente trabalha na catarse e ministra cursos na Caelum."
    company: "Catarse / Caelum (RJ)"
    twitter: "pedromarins"
    presentation:
      title: ""
      description: ""
      time: "14h00"
  -
    name: "Rodrigo Nogueira"
    photo: "/img/speakers/rodrigo.jpg"
    bio: "Aficionado por tecnologia, começou a trabalhar como Desenvolvedor Web em 2008 desenvolvendo sistemas e sites. Formado em Sistemas para Internet pela Faculdade Marista, também passou a dar aulas no 4º período com o consenso do coordenador do curso da Faculdade. Trabalhou como Front-End para uma das maiores agências do mundo, a Ogilvy e a maior startup do Brasil o Peixe Urbano. Atualmente esta ministrando um treinamento para front-ends na Fator Web e atuando como Front-End na Parafernália Interativa."
    company: "Parafernália Interativa (RJ)"
    twitter: "fale_rodrigo"
    presentation:
      title: "O Mercado Front-End no Brasil e no Mundo"
      description: "Uma apanhado geral do profissional Front-End onde mostro médias salariais por região, diferenças na valorização do profissional nordestino, dicas para ser valorizado profissionalmente, como trabalhar home-office e mais dicas pra quem quer trabalhar como Front-End nos EUA."
      time: "14h00"
  -
    name: "Shankar Cabus"
    photo: "http://graph.facebook.com/shankarcabus/picture?type=large"
    bio: "Sobrinho desde 2001, sempre foi apaixonado pela Web e tudo que a cerca. Graduado em Sistema de Informação pela UNEB, trabalha oficialmente com front-end desde 2009 no JusBrasil, onde aprendeu a pensar focado no usuário. É também fundador do grupo Frontend Bahia e CSS lover <3"
    company: "JusBrasil (BA)"
    twitter: "shankarcabus"
    presentation:
      title: "O Poder Está No Frontend"
      description: "Afinal, o que é o front-end? Qual profissional faz o front-end? Por que aprender front-end? Vamos desmistificar alguns assuntos polêmicos e mostrar o poder do front-end de uma forma bem humorada e criativa ;)"
      time: "14h00"

# List of Sponsors
sponsors:
  -
    name: "Eventick"
    logo: "http://f.cl.ly/items/1U3p0Z0e2w0I1i3z1X22/Image%202012.09.25%203:00:58%20PM.png"
    url: "http://eventick.com.br"

# List of Partners
partners:
  -
    name: "BrazilJS"
    logo: "img/sponsor/braziljs.png"
    url: "http://braziljs.org"
  -
    name: "Eventick"
    logo: "img/sponsor/eventick.png"
    url: "http://www.eventick.com.br/"
  -
    name: "Faculdade Marista"
    logo: "img/sponsor/marista.png"
    url: "http://faculdademarista.com.br/"
  -
    name: "MGR Tech"
    logo: "img/sponsor/mgrtech.png"
    url: "http://mgrtech.com.br/"
  -
    name: "Front in BH"
    logo: "img/sponsor/frontinbh.png"
    url: "http://frontinbh.com.br/"
  -
    name: "Frontend Bahia"
    logo: "img/sponsor/frontendba.png"
    url: "https://www.facebook.com/groups/frontendbahia/"
